### PR TITLE
docs: initial commit for "search"

### PR DESCRIPTION
**Pull request by rchincha**
This work is relevant for both CNCF (artifacts) and OCI (distribution spec)

We can iterate under CNCF for this part while being compatible with OCI.

### CODE REVIEW

**Comment by rchincha** [comment]
cc: @SteveLasker @ktarplee @sabre1041 @sudo-bmitch

**Comment by rchincha** [comment]
Maybe /v2/_artifacts?

**Comment by rchincha** [comment]
https://github.com/oras-project/oras/discussions/1257

**Comment by rchincha** [comment]
https://github.com/project-zot/zot/blob/main/pkg/extensions/search/search.md

zot already supports these but specific to zot

**Comment by rchincha** [comment]
https://github.com/project-zot/zot/pull/2209

Reachable as follows ...


```
$ curl http://localhost:8080/v2/_artifacts/ext/search

{"errors":[{"message":"no operation provided","extensions":{"code":"GRAPHQL_VALIDATION_FAILED"}}],"data":null}
```

**Comment by sabre1041** [comment]
This is a great start @rchincha 

Would you be able to take a look at the CI failures?

**Review by sudo-bmitch — APPROVED** [review]
This LGTM as a starting point. I'm fine with merging and iterating.

**Pull request merged**
