### PR TITLE
docs: added alpine pkgmgr

### LINKED ISSUE #15: Add Alpine packages as a use case

### PR DESCRIPTION
**Pull request by ktarplee**
Closes #15

### CODE REVIEW

**Comment by rchincha** [comment]
Some conflicts and actual cmd invocations would be nice (can add it to the conformance tests)

**Review by SteveLasker — APPROVED** [review]
LGTM

**Comment by afflom** [comment]
@ktarplee conflict as you predicted.

**Review by afflom — APPROVED** [review]

**Comment by ktarplee** [comment]
@afflom Conflicts are resolved.  This should be ready.

**Pull request merged**
