### PR TITLE
docs: add a npm query support document

### PR DESCRIPTION
**Pull request by rchincha**
Partly fixes issue #12

### CODE REVIEW

**Comment by rchincha** [comment]
cc: @SteveLasker

**Review by SteveLasker — APPROVED** [review]
thanks, @rchincha
LGTM

**Comment by ktarplee** [comment]
Given that ultimately the goal is to design an API for a remote data store (OCI) do we really care about the commands-level details.  I feel we care more about boiling it down a little more and documenting how these commands interact with a local or remote data store.  The actual commands that need to be issued to create HTTP requests or local file system access are not of first-class important here.  They seem to be noise in our assessment of these package management systems.

**Comment by SteveLasker** [comment]
I think your point about the end goal is very accurate. I look at this PR, in its present state, as a starting point to say these are the commands for each package manager to start from, and then understand how they work. 
Knowing the parameters they expose: (how much info is required vs. optional), and what they return for a given scenario helps scope what problems they solve. 
If we think that's a good scope, and the feedback for that package manager community believes it's solid, it suggests we can dig deeper to leverage it. 
If the package manager community feels it was close, but missing _x_, _y_, _z_, that would be good input to improve. 

So, yes, we need more detail, but is this a good starting point to identify the details?

**Pull request merged**
