### PR TITLE
Use Cases

### PR DESCRIPTION
**Pull request by SteveLasker**
A sketch for how we can capture use cases across different package managers.

### CODE REVIEW

**Comment by afflom** [comment]
@SteveLasker , Great work on this. 

lgtm

@rchincha ptal

**Comment by SteveLasker** [comment]
I've updated to match the folder structure of #5

**Comment by SteveLasker** [comment]
Question on the linter:
> Error: docs/use-cases.md:6:13 MD033/no-inline-html Inline HTML [Element: BR] https://github.com/DavidAnson/markdownlint/blob/v0.30.0/doc/md033.md

How formal do we feel about this? 
~~Is there a way to do inline exceptions?~~
Yes: `<!-- markdownlint-disable-next-line MD033 -->` See [Configuration](https://github.com/DavidAnson/markdownlint/tree/v0.30.0#configuration)

**Review by rchincha — APPROVED** [review]
lgtm

This is a good "initial commit"

**Pull request merged**
