### PR TITLE
feat: add a pkg mgmt onboarding issue template

### PR DESCRIPTION
**Pull request by rchincha**
Fixes issue #2

### CODE REVIEW

**Comment by SteveLasker** [comment]
Thanks, @rchincha
I copied the output to a [test repo](https://github.com/SteveLasker/scratch/issues/new/choose) and filled it out to see what it would look like for a contributor: 
There's a lot of great information captured, but also wondering if it's steep for engaging package manager devs wanting to participate. And, how would contributors iterate on the contents of the issue? The owner of the issue could keep editing...
I'm also wondering what we'd do with the issue as issues tend to be relatively short-lived tracking items. Do we want to track all the package managers as issues, or should we capture these as markdown files within the repo for longevity and reference? 
Another approach might be to create a markdown template package-managers/package-tempalte.md and ask folks to copy the template and make iterative PRs to that description. This way there's a low bar to get the package managers added, and we can iterate on the contents with several folks contributing. 

We likely still want to track various package managers to submit the markdown template, but could the contents of the template be a bit lighter?

```
title: "[PkgMgmt]: <name>"
labels: ["pkgmgmt"]
body:
  - type: textarea
    attributes:
      label: "Describe the package management system"
      description: "Try to describe your package management system as well as you can, as that will help with speeding up onboarding"
  - type: textarea
    attributes:
      label: "Package Manager Tracking Issue?"
      description: "Links to requests to participate in the package manager ecosystem"
```

**Comment by afflom** [comment]
Thank you for tackling this @rchincha.

> Thanks, @rchincha I copied the output to a [test repo](https://github.com/SteveLasker/scratch/issues/new/choose) and filled it out to see what it would look like for a contributor: There's a lot of great information captured, but also wondering if it's steep for engaging package manager devs wanting to participate. And, how would contributors iterate on the contents of the issue? The owner of the issue could keep editing... I'm also wondering what we'd do with the issue as issues tend to be relatively short-lived tracking items. Do we want to track all the package managers as issues, or should we capture these as markdown files within the repo for longevity and reference? Another approach might be to create a markdown template package-managers/package-tempalte.md and ask folks to copy the template and make iterative PRs to that description. This way there's a low bar to get the package managers added, and we can iterate on the contents with several folks contributing.
> 
> We likely still want to track various package managers to submit the markdown template, but could the contents of the template be a bit lighter?
> 


I'm on the fence. I like the proposed template, but also understand @SteveLasker's apprehension with the seemingly steep requirements for submission and the short-lived nature of GH Issues. Can we find a compromise here, where package manager maintainers submit issues, have a discussion about the specifics with the working group in that thread, and then close the issue with a PR that commits the discovered information to the repo?

**Comment by rchincha** [comment]
@afflom @SteveLasker 
If we already know where those PRs would write to (pkgmgr/* perhaps) we can just make it a generic markdown template so folks can submit a PR.

**Comment by SteveLasker** [comment]
@rchincha, absolutely, 👍

**Comment by rchincha** [comment]
Working on porting this into a template in the repo itself.

**Comment by rchincha** [comment]
Fixed, please take a look.

**Review by afflom — APPROVED** [review]
lgtm. @SteveLasker, please confirm before I merge.

**Review by SteveLasker — APPROVED** [review]
LGTM, thank you @rchincha for the iterations

**Pull request merged**
